void* drmAddBufs () { return 0; }
void* drmAddContextPrivateMapping () { return 0; }
void* drmAddContextTag () { return 0; }
void* drmAddMap () { return 0; }
void* drmAgpAcquire () { return 0; }
void* drmAgpAlloc () { return 0; }
void* drmAgpBase () { return 0; }
void* drmAgpBind () { return 0; }
void* drmAgpDeviceId () { return 0; }
void* drmAgpEnable () { return 0; }
void* drmAgpFree () { return 0; }
void* drmAgpGetMode () { return 0; }
void* drmAgpMemoryAvail () { return 0; }
void* drmAgpMemoryUsed () { return 0; }
void* drmAgpRelease () { return 0; }
void* drmAgpSize () { return 0; }
void* drmAgpUnbind () { return 0; }
void* drmAgpVendorId () { return 0; }
void* drmAgpVersionMajor () { return 0; }
void* drmAgpVersionMinor () { return 0; }
void* drmAuthMagic () { return 0; }
void* drmAvailable () { return 0; }
void* drmCheckModesettingSupported () { return 0; }
void* drmClose () { return 0; }
void* drmCloseBufferHandle () { return 0; }
void* drmCloseOnce () { return 0; }
void* drmCommandNone () { return 0; }
void* drmCommandRead () { return 0; }
void* drmCommandWrite () { return 0; }
void* drmCommandWriteRead () { return 0; }
void* drmCreateContext () { return 0; }
void* drmCreateDrawable () { return 0; }
void* drmCrtcGetSequence () { return 0; }
void* drmCrtcQueueSequence () { return 0; }
void* drmCtlInstHandler () { return 0; }
void* drmCtlUninstHandler () { return 0; }
void* drmDelContextTag () { return 0; }
void* drmDestroyContext () { return 0; }
void* drmDestroyDrawable () { return 0; }
void* drmDevicesEqual () { return 0; }
void* drmDMA () { return 0; }
void* drmDropMaster () { return 0; }
void* drmError () { return 0; }
void* drmFinish () { return 0; }
void* drmFree () { return 0; }
void* drmFreeBufs () { return 0; }
void* drmFreeBusid () { return 0; }
void* drmFreeDevice () { return 0; }
void* drmFreeDevices () { return 0; }
void* drmFreeReservedContextList () { return 0; }
void* drmFreeVersion () { return 0; }
void* drmGetBufInfo () { return 0; }
void* drmGetBusid () { return 0; }
void* drmGetCap () { return 0; }
void* drmGetClient () { return 0; }
void* drmGetContextFlags () { return 0; }
void* drmGetContextPrivateMapping () { return 0; }
void* drmGetContextTag () { return 0; }
void* drmGetDevice () { return 0; }
void* drmGetDevice2 () { return 0; }
void* drmGetDeviceFromDevId () { return 0; }
void* drmGetDeviceNameFromFd () { return 0; }
void* drmGetDeviceNameFromFd2 () { return 0; }
void* drmGetDevices () { return 0; }
void* drmGetDevices2 () { return 0; }
void* drmGetEntry () { return 0; }
void* drmGetFormatModifierName () { return 0; }
void* drmGetFormatModifierVendor () { return 0; }
void* drmGetFormatName () { return 0; }
void* drmGetHashTable () { return 0; }
void* drmGetInterruptFromBusID () { return 0; }
void* drmGetLibVersion () { return 0; }
void* drmGetLock () { return 0; }
void* drmGetMagic () { return 0; }
void* drmGetMap () { return 0; }
void* drmGetNodeTypeFromDevId () { return 0; }
void* drmGetNodeTypeFromFd () { return 0; }
void* drmGetPrimaryDeviceNameFromFd () { return 0; }
void* drmGetRenderDeviceNameFromFd () { return 0; }
void* drmGetReservedContextList () { return 0; }
void* drmGetStats () { return 0; }
void* drmGetVersion () { return 0; }
void* drmHandleEvent () { return 0; }
void* drmHashCreate () { return 0; }
void* drmHashDelete () { return 0; }
void* drmHashDestroy () { return 0; }
void* drmHashFirst () { return 0; }
void* drmHashInsert () { return 0; }
void* drmHashLookup () { return 0; }
void* drmHashNext () { return 0; }
void* drmIoctl () { return 0; }
void* drmIsKMS () { return 0; }
void* drmIsMaster () { return 0; }
void* drmMalloc () { return 0; }
void* drmMap () { return 0; }
void* drmMapBufs () { return 0; }
void* drmMarkBufs () { return 0; }
void* drmModeAddFB () { return 0; }
void* drmModeAddFB2 () { return 0; }
void* drmModeAddFB2WithModifiers () { return 0; }
void* drmModeAtomicAddProperty () { return 0; }
void* drmModeAtomicAlloc () { return 0; }
void* drmModeAtomicCommit () { return 0; }
void* drmModeAtomicDuplicate () { return 0; }
void* drmModeAtomicFree () { return 0; }
void* drmModeAtomicGetCursor () { return 0; }
void* drmModeAtomicMerge () { return 0; }
void* drmModeAtomicSetCursor () { return 0; }
void* drmModeAttachMode () { return 0; }
void* drmModeCloseFB () { return 0; }
void* drmModeConnectorGetPossibleCrtcs () { return 0; }
void* drmModeConnectorSetProperty () { return 0; }
void* drmModeCreateDumbBuffer () { return 0; }
void* drmModeCreateLease () { return 0; }
void* drmModeCreatePropertyBlob () { return 0; }
void* drmModeCrtcGetGamma () { return 0; }
void* drmModeCrtcSetGamma () { return 0; }
void* drmModeDestroyDumbBuffer () { return 0; }
void* drmModeDestroyPropertyBlob () { return 0; }
void* drmModeDetachMode () { return 0; }
void* drmModeDirtyFB () { return 0; }
void* drmModeFormatModifierBlobIterNext () { return 0; }
void* drmModeFreeConnector () { return 0; }
void* drmModeFreeCrtc () { return 0; }
void* drmModeFreeEncoder () { return 0; }
void* drmModeFreeFB () { return 0; }
void* drmModeFreeFB2 () { return 0; }
void* drmModeFreeModeInfo () { return 0; }
void* drmModeFreeObjectProperties () { return 0; }
void* drmModeFreePlane () { return 0; }
void* drmModeFreePlaneResources () { return 0; }
void* drmModeFreeProperty () { return 0; }
void* drmModeFreePropertyBlob () { return 0; }
void* drmModeFreeResources () { return 0; }
void* drmModeGetConnector () { return 0; }
void* drmModeGetConnectorCurrent () { return 0; }
void* drmModeGetConnectorTypeName () { return 0; }
void* drmModeGetCrtc () { return 0; }
void* drmModeGetEncoder () { return 0; }
void* drmModeGetFB () { return 0; }
void* drmModeGetFB2 () { return 0; }
void* drmModeGetLease () { return 0; }
void* drmModeGetPlane () { return 0; }
void* drmModeGetPlaneResources () { return 0; }
void* drmModeGetProperty () { return 0; }
void* drmModeGetPropertyBlob () { return 0; }
void* drmModeGetResources () { return 0; }
void* drmModeListLessees () { return 0; }
void* drmModeMapDumbBuffer () { return 0; }
void* drmModeMoveCursor () { return 0; }
void* drmModeObjectGetProperties () { return 0; }
void* drmModeObjectSetProperty () { return 0; }
void* drmModePageFlip () { return 0; }
void* drmModePageFlipTarget () { return 0; }
void* drmModeRevokeLease () { return 0; }
void* drmModeRmFB () { return 0; }
void* drmModeSetCrtc () { return 0; }
void* drmModeSetCursor () { return 0; }
void* drmModeSetCursor2 () { return 0; }
void* drmModeSetPlane () { return 0; }
void* drmMsg () { return 0; }
void* drmOpen () { return 0; }
void* drmOpenControl () { return 0; }
void* drmOpenOnce () { return 0; }
void* drmOpenOnceWithType () { return 0; }
void* drmOpenRender () { return 0; }
void* drmOpenWithType () { return 0; }
void* drmPrimeFDToHandle () { return 0; }
void* drmPrimeHandleToFD () { return 0; }
void* drmRandom () { return 0; }
void* drmRandomCreate () { return 0; }
void* drmRandomDestroy () { return 0; }
void* drmRandomDouble () { return 0; }
void* drmRmMap () { return 0; }
void* drmScatterGatherAlloc () { return 0; }
void* drmScatterGatherFree () { return 0; }
void* drmSetBusid () { return 0; }
void* drmSetClientCap () { return 0; }
void* drmSetContextFlags () { return 0; }
void* drmSetInterfaceVersion () { return 0; }
void* drmSetMaster () { return 0; }
void* drmSetServerInfo () { return 0; }
void* drmSLCreate () { return 0; }
void* drmSLDelete () { return 0; }
void* drmSLDestroy () { return 0; }
void* drmSLDump () { return 0; }
void* drmSLFirst () { return 0; }
void* drmSLInsert () { return 0; }
void* drmSLLookup () { return 0; }
void* drmSLLookupNeighbors () { return 0; }
void* drmSLNext () { return 0; }
void* drmSwitchToContext () { return 0; }
void* drmSyncobjCreate () { return 0; }
void* drmSyncobjDestroy () { return 0; }
void* drmSyncobjEventfd () { return 0; }
void* drmSyncobjExportSyncFile () { return 0; }
void* drmSyncobjFDToHandle () { return 0; }
void* drmSyncobjHandleToFD () { return 0; }
void* drmSyncobjImportSyncFile () { return 0; }
void* drmSyncobjQuery () { return 0; }
void* drmSyncobjQuery2 () { return 0; }
void* drmSyncobjReset () { return 0; }
void* drmSyncobjSignal () { return 0; }
void* drmSyncobjTimelineSignal () { return 0; }
void* drmSyncobjTimelineWait () { return 0; }
void* drmSyncobjTransfer () { return 0; }
void* drmSyncobjWait () { return 0; }
void* drmUnlock () { return 0; }
void* drmUnmap () { return 0; }
void* drmUnmapBufs () { return 0; }
void* drmUpdateDrawableInfo () { return 0; }
void* drmWaitVBlank () { return 0; }
